version: "3"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"

  redis:
    image: redis
  
  node:
    image: node:10-slim
    # ports:
    #   - "80:8080"

  app:
    build: .
    depends_on:
      - mysql
      - redis
      - node
    ports:
      - "3000:3000"