version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456

  redis:
    image: redis
    ports:
      - "6379:6379"
  
  node:
    image: node:10-slim

  app:
    build: .
    depends_on:
      - db
      - redis
      - node
    ports:
      - "3000:3000"
    environment: 
      APP_DB_HOST: db:3306
      APP_DB_USER: root
      APP_DB_PASSWORD: 123456
